version: 0.0
Resources:
  - TargetService:
      Type: AWS::EC2::Instance
      Properties:
        LogicalName: MyEC2Instance
        Name: test
        ScriptPath: scripts/
        TimeoutInSeconds: 3600
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
